### ISSUE TITLE
Multiple deprecation warnings

### ISSUE THREAD

**Issue by roncapat** [rubysamurai/material_components_web-sass#7]
Rails Puma server starts properly, but outputs those warnings. I put them here to let you know, in case you don't.

```
DEPRECATION WARNING on line 34 of /usr/local/rvm/gems/ruby-2.3.0/gems/material_components_web-sass-0.23.0/vendor/assets/stylesheets/@material/drawer/_mixins.scss:
#{} interpolation near operators will be simplified in a future version of Sass.
To preserve the current behavior, use quotes:

  unquote("#{&}")

DEPRECATION WARNING on line 22 of /usr/local/rvm/gems/ruby-2.3.0/gems/material_components_web-sass-0.23.0/vendor/assets/stylesheets/@material/layout-grid/_mixins.scss:
The result of `0px != 0` will be `true` in future releases of Sass.
Unitless numbers will no longer be equal to the same numbers with units.
```

**Comment by rubysamurai** [comment]
These deprecation warnings exist in original MDC source Sass files ([here for layout grid](https://github.com/material-components/material-components-web/blob/745597838c4a3f67dcbe0f894c2e1923b0d15052/packages/mdc-layout-grid/_mixins.scss#L22) and [here for drawer](https://github.com/material-components/material-components-web/blob/745597838c4a3f67dcbe0f894c2e1923b0d15052/packages/mdc-drawer/_mixins.scss#L34)) when compiled with Ruby Sass. 

So this issue have to be fixed in the upstream MDC source files, but I suppose it is not a priority for MDC team as it doesn't prevent proper compilation for now.

**Comment by roncapat** [comment]
Thank you for super-quick response.

Il ven 20 ott 2017, 14:20 Dmitriy Tarasov <notifications@github.com> ha
scritto:
